import React, { useEffect, useState } from 'react';
import { Bell, BookOpen, Check, ChevronRight, CloudSun, Droplets, FileText, HelpCircle, IndianRupee, Mail, MapPin, MessageCircle, Save, Search, Settings, Sprout, Sun, ThermometerSun, UserRound, Users, Wind } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { MOCK_PRODUCTS } from '../services/mockData';
import { Modal, SearchBar, StatCard, EmptyState } from '../components/UIComponents';

const WEATHER = [
  { day: 'Today', icon: Sun, temp: '31°', rain: '10%', note: 'Clear skies' },
  { day: 'Tue', icon: CloudSun, temp: '29°', rain: '25%', note: 'Partly cloudy' },
  { day: 'Wed', icon: CloudSun, temp: '28°', rain: '40%', note: 'Cloudy' },
  { day: 'Thu', icon: Droplets, temp: '27°', rain: '65%', note: 'Light showers' },
  { day: 'Fri', icon: Sun, temp: '30°', rain: '15%', note: 'Sunny' },
];

const SCHEMES = [
  { title: 'PM-KISAN Samman Nidhi', tag: 'Income Support', body: 'Direct income support for eligible landholding farmer families.', amount: '₹6,000 / year', deadline: 'Open throughout the year' },
  { title: 'Pradhan Mantri Fasal Bima Yojana', tag: 'Crop Insurance', body: 'Affordable crop insurance cover for weather and yield losses.', amount: 'Premium from 1.5%', deadline: 'Before sowing season' },
  { title: 'Kisan Credit Card', tag: 'Credit', body: 'Flexible working capital for crops, allied activities, and farm needs.', amount: 'Low-interest credit', deadline: 'Apply anytime' },
  { title: 'Soil Health Card', tag: 'Advisory', body: 'Get soil testing and crop-specific nutrient recommendations.', amount: 'Free testing', deadline: 'Book a slot' },
];

const POSTS = [
  { name: 'Sukhdev Singh', place: 'Ludhiana, Punjab', time: '2h ago', text: 'The mustard crop is looking strong after the recent rain. What price are farmers seeing near your mandi?', likes: 18, replies: 6 },
  { name: 'Lakshmi Devi', place: 'Nashik, Maharashtra', time: '5h ago', text: 'Sharing a simple drip irrigation schedule that helped reduce water use for tomatoes this season.', likes: 31, replies: 11 },
  { name: 'Ramesh Kumar', place: 'Karnal, Haryana', time: 'Yesterday', text: 'Looking for a reliable FPO transport partner for a 2-ton wheat shipment to Delhi.', likes: 12, replies: 4 },
];

const NOTIFICATIONS = [
  { title: 'Your wheat order is in transit', detail: 'ORD-20260908 is expected tomorrow.', type: 'Order', read: false },
  { title: 'Tomato demand is rising', detail: 'Demand in Delhi is forecast to rise 6% this week.', type: 'Market', read: false },
  { title: 'New scheme reminder', detail: 'Check your eligibility for PM Fasal Bima Yojana.', type: 'Government', read: true },
];

export function ProfilePage() {
  const { user, addToast, t } = useApp();
  const [profile, setProfile] = useState(() => JSON.parse(localStorage.getItem('krishisetu_profile') || 'null') || { name: user?.name || 'Ramesh Kumar', phone: '9812345678', village: user?.location || 'Karnal', state: 'Haryana', crops: 'Wheat, Maize, Mustard' });
  const save = () => { localStorage.setItem('krishisetu_profile', JSON.stringify(profile)); addToast(t('Profile saved locally'), 'success'); };
  return <PageShell title="My Profile" subtitle="Keep your farmer profile ready for buyers and community members.">
    <div className="grid lg:grid-cols-3 gap-6"><div className="card lg:col-span-2 space-y-4"><div className="flex items-center gap-4 pb-4 border-b border-gray-100"><div className="w-16 h-16 rounded-2xl bg-forest-100 flex items-center justify-center text-2xl font-bold text-forest-800">{profile.name[0]}</div><div><h2 className="text-xl font-bold text-forest-800">{profile.name}</h2><p className="text-sm text-agri-muted">Farmer profile · Demo account</p></div></div><div className="grid sm:grid-cols-2 gap-4">{[['name','Full name'],['phone','Mobile number'],['village','Village / city'],['state','State'],['crops','Main crops']].map(([key,label]) => <label key={key} className="label">{label}<input className="input mt-1" value={profile[key]} onChange={e => setProfile({ ...profile, [key]: e.target.value })} /></label>)}</div><button className="btn-primary" onClick={save}><Save size={16} />Save Profile</button></div><div className="card bg-forest-800 text-white"><UserRound size={22} className="text-forest-200 mb-5" /><p className="text-xs text-forest-200 uppercase tracking-wider">Profile completeness</p><div className="text-4xl font-bold mt-2">80%</div><div className="h-2 bg-forest-700 rounded-full mt-4"><div className="h-2 bg-green-300 rounded-full w-4/5" /></div><p className="text-sm text-forest-200 mt-5">Add your farm size and preferred market to improve recommendations.</p></div></div>
  </PageShell>;
}

export function WeatherPage() { return <PageShell title="Weather Dashboard" subtitle="Local weather guidance for your farm activities."><div className="card bg-gradient-to-br from-forest-800 to-forest-700 text-white mb-6"><div className="flex flex-wrap items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-forest-200 text-sm"><MapPin size={15} /> Karnal, Haryana</div><div className="text-6xl font-bold mt-5">31°C</div><p className="text-forest-200 mt-2">Clear skies · Good conditions for field work</p></div><Sun size={76} className="text-yellow-200" /></div><div className="grid grid-cols-3 gap-4 mt-8 pt-5 border-t border-forest-600"><div><p className="text-xs text-forest-200">Humidity</p><p className="font-bold mt-1">48%</p></div><div><p className="text-xs text-forest-200">Wind</p><p className="font-bold mt-1">12 km/h</p></div><div><p className="text-xs text-forest-200">UV Index</p><p className="font-bold mt-1">Moderate</p></div></div></div><div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mb-6">{WEATHER.map(({ day, icon: Icon, temp, rain, note }) => <div className="card p-4 text-center" key={day}><p className="text-xs font-bold text-forest-700">{day}</p><Icon size={28} className="mx-auto my-4 text-orange-400" /><p className="text-xl font-bold text-forest-800">{temp}</p><p className="text-xs text-blue-600 mt-1">{rain} rain</p><p className="text-[11px] text-agri-muted mt-2">{note}</p></div>)}</div><div className="card"><h3 className="font-bold text-forest-800 mb-4">Farm advisory</h3><div className="grid md:grid-cols-3 gap-4"><Advice icon={Droplets} title="Irrigation" text="Water early morning tomorrow. Avoid overwatering after Thursday showers." /><Advice icon={ThermometerSun} title="Crop care" text="Good conditions for field inspection and pest scouting today." /><Advice icon={Wind} title="Spraying" text="Avoid spraying on Thursday due to higher rain probability." /></div></div></PageShell>; }

function Advice({ icon: Icon, title, text }) { return <div className="p-4 rounded-xl bg-forest-50 border border-forest-100"><Icon size={18} className="text-forest-700 mb-3" /><p className="font-semibold text-forest-800 text-sm">{title}</p><p className="text-xs text-gray-600 mt-1 leading-relaxed">{text}</p></div>; }

export function MarketPricesPage() { const [query, setQuery] = useState(''); const [market, setMarket] = useState('All markets'); const products = MOCK_PRODUCTS.filter(p => `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()) && (market === 'All markets' || p.state === market)); return <PageShell title="Mandi Prices" subtitle="Compare indicative prices across the Krishi Setu network."><div className="card mb-6"><div className="flex flex-col sm:flex-row gap-3"><SearchBar value={query} onChange={setQuery} placeholder="Search crop or commodity..." className="flex-1" /><select className="select sm:max-w-xs" value={market} onChange={e => setMarket(e.target.value)}><option>All markets</option><option>Haryana</option><option>Punjab</option><option>Maharashtra</option><option>Gujarat</option></select></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><StatCard icon={IndianRupee} label="Best price today" value="₹95/kg" subtext="Red Apples" color="green" /><StatCard icon={TrendingIcon} label="Rising crops" value="6" subtext="Across 4 markets" color="blue" /><StatCard icon={MapPin} label="Markets tracked" value="18" subtext="Indicative demo data" color="orange" /><StatCard icon={Sprout} label="Your opportunity" value="+8%" subtext="Average price trend" color="purple" /></div><div className="card"><div className="table-wrapper border-0"><table className="table"><thead><tr><th>Crop</th><th>Market</th><th>Grade</th><th>Indicative price</th><th>Trend</th></tr></thead><tbody>{products.map(p => <tr key={p._id}><td className="font-semibold">{p.image} {p.name}</td><td>{p.location}, {p.state}</td><td>Grade {p.quality}</td><td className="font-bold text-forest-700">₹{p.price}/kg</td><td><span className="text-green-600 font-semibold">↑ 4.2%</span></td></tr>)}</tbody></table></div>{!products.length && <EmptyState icon={Search} title="No crops found" description="Try another crop or market." />}</div></PageShell>; }
function TrendingIcon(props) { return <span {...props}>↗</span>; }

export function SchemesPage() { const [query, setQuery] = useState(''); const filtered = SCHEMES.filter(s => `${s.title} ${s.tag}`.toLowerCase().includes(query.toLowerCase())); return <PageShell title="Government Schemes" subtitle="Discover support programmes relevant to your farm."><div className="card mb-6"><SearchBar value={query} onChange={setQuery} placeholder="Search schemes, insurance, credit..." /></div><div className="grid md:grid-cols-2 gap-5">{filtered.map(s => <div className="card-hover" key={s.title}><div className="flex items-start justify-between gap-3"><div className="w-11 h-11 rounded-xl bg-green-100 flex items-center justify-center"><FileText size={20} className="text-green-700" /></div><span className="badge bg-forest-50 text-forest-700">{s.tag}</span></div><h3 className="font-bold text-forest-800 mt-5">{s.title}</h3><p className="text-sm text-gray-600 mt-2 leading-relaxed">{s.body}</p><div className="flex justify-between items-end mt-5 pt-4 border-t border-gray-100"><div><p className="text-xs text-agri-muted">Benefit</p><p className="font-semibold text-green-700">{s.amount}</p></div><div className="text-right"><p className="text-xs text-agri-muted">Status</p><p className="text-sm font-semibold text-forest-700">{s.deadline}</p></div></div><button className="btn-secondary w-full justify-center mt-5">View eligibility <ChevronRight size={15} /></button></div>)}</div></PageShell>; }

export function CommunityPage() { const [posts, setPosts] = useState(POSTS); const [draft, setDraft] = useState(''); const [liked, setLiked] = useState([]); const publish = () => { if (!draft.trim()) return; setPosts([{ name: 'You', place: 'Karnal, Haryana', time: 'Just now', text: draft, likes: 0, replies: 0 }, ...posts]); setDraft(''); }; return <PageShell title="Farmer Community" subtitle="Learn from fellow farmers, FPOs, and local experts."><div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-4"><div className="card"><textarea className="input resize-none h-24" placeholder="Share a crop update, question, or tip..." value={draft} onChange={e => setDraft(e.target.value)} /><div className="flex justify-between items-center mt-3"><span className="text-xs text-agri-muted">Be respectful and useful to the community.</span><button className="btn-primary" onClick={publish}>Post update</button></div></div>{posts.map((post, index) => <div className="card" key={`${post.name}-${index}`}><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-forest-100 text-forest-800 flex items-center justify-center font-bold">{post.name[0]}</div><div><p className="font-semibold text-gray-800">{post.name}</p><p className="text-xs text-agri-muted">{post.place} · {post.time}</p></div></div><p className="text-sm text-gray-700 leading-relaxed mt-4">{post.text}</p><div className="flex gap-5 mt-4 pt-3 border-t border-gray-100"><button className={`text-xs font-semibold ${liked.includes(index) ? 'text-green-700' : 'text-gray-500'}`} onClick={() => setLiked(liked.includes(index) ? liked.filter(i => i !== index) : [...liked, index])}>♡ {post.likes + (liked.includes(index) ? 1 : 0)} Helpful</button><button className="text-xs font-semibold text-gray-500">💬 {post.replies} Replies</button></div></div>)}</div><div className="card h-fit"><Users size={20} className="text-forest-700" /><h3 className="font-bold text-forest-800 mt-4">Popular groups</h3>{['Wheat growers', 'FPO leaders', 'Organic farming', 'Mandi updates'].map((group, i) => <div className="flex items-center justify-between py-3 border-b border-gray-100 last:border-0" key={group}><span className="text-sm text-gray-700">{group}</span><span className="text-xs text-agri-muted">{[124, 86, 64, 210][i]} members</span></div>)}</div></div></PageShell>; }

export function NotificationsPage() { const [items, setItems] = useState(NOTIFICATIONS); return <PageShell title="Notifications" subtitle="Stay up to date with orders, markets, and schemes."><div className="flex justify-end mb-4"><button className="btn-ghost text-sm" onClick={() => setItems(items.map(item => ({ ...item, read: true })))}><Check size={15} />Mark all as read</button></div><div className="card p-0 overflow-hidden">{items.map((item, i) => <button className={`w-full text-left flex gap-4 p-5 border-b border-gray-100 last:border-0 hover:bg-gray-50 ${item.read ? '' : 'bg-green-50/50'}`} key={i} onClick={() => setItems(items.map((n, index) => index === i ? { ...n, read: true } : n))}><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${item.type === 'Order' ? 'bg-blue-100 text-blue-700' : item.type === 'Market' ? 'bg-green-100 text-green-700' : 'bg-orange-100 text-orange-700'}`}><Bell size={18} /></div><div className="flex-1"><div className="flex items-center gap-2"><p className="font-semibold text-gray-800 text-sm">{item.title}</p>{!item.read && <span className="w-2 h-2 rounded-full bg-green-500" />}</div><p className="text-sm text-gray-600 mt-1">{item.detail}</p><span className="text-xs text-agri-muted mt-2 inline-block">{item.type}</span></div><ChevronRight size={17} className="text-gray-400 mt-2" /></button>)}</div></PageShell>; }

export function ChatPage() { const [active, setActive] = useState(0); const [message, setMessage] = useState(''); const [messages, setMessages] = useState([['Sukhdev Singh', 'Hello! Are you looking for wheat for the next dispatch?'], ['You', 'Yes, I need around 500 kg for Delhi.']]); const send = () => { if (!message.trim()) return; setMessages([...messages, ['You', message]]); setMessage(''); }; return <PageShell title="Messages" subtitle="Coordinate with farmers and buyers in the demo inbox."><div className="card p-0 overflow-hidden grid md:grid-cols-3 min-h-[520px]"><div className="border-r border-gray-100"><div className="p-4 border-b border-gray-100"><SearchBar value="" onChange={() => {}} placeholder="Search messages" /></div>{['Sukhdev Singh', 'Lakshmi Devi', 'Vikram Traders'].map((name, i) => <button key={name} className={`w-full text-left p-4 flex gap-3 border-b border-gray-100 ${active === i ? 'bg-forest-50' : 'hover:bg-gray-50'}`} onClick={() => setActive(i)}><div className="w-9 h-9 rounded-full bg-forest-100 text-forest-800 flex items-center justify-center font-bold">{name[0]}</div><div><p className="font-semibold text-sm text-gray-800">{name}</p><p className="text-xs text-agri-muted mt-1">Last message · 2h ago</p></div></button>)}</div><div className="md:col-span-2 flex flex-col"><div className="p-4 border-b border-gray-100 flex items-center gap-3"><MessageCircle size={19} className="text-forest-700" /><div><p className="font-semibold text-gray-800">{['Sukhdev Singh', 'Lakshmi Devi', 'Vikram Traders'][active]}</p><p className="text-xs text-green-600">Available in demo</p></div></div><div className="flex-1 p-5 space-y-3 bg-gray-50">{messages.map(([from, text], i) => <div className={`flex ${from === 'You' ? 'justify-end' : 'justify-start'}`} key={i}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${from === 'You' ? 'bg-forest-800 text-white rounded-br-sm' : 'bg-white text-gray-700 rounded-bl-sm shadow-sm'}`}>{text}</div></div>)}</div><div className="p-4 border-t border-gray-100 flex gap-2"><input className="input" value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Write a message..." /><button className="btn-primary px-4" onClick={send}>Send</button></div></div></div></PageShell>; }

export function HelpPage() { const [open, setOpen] = useState(null); const faqs = [['How do I list produce?', 'Open Add Produce from the farmer menu, enter your crop details, and save. Your listing is stored in this browser for the demo.'], ['How are prices shown?', 'Mandi prices are indicative demo data. Use them to compare crops and markets before deciding what to list.'], ['Can I contact a buyer?', 'Use Messages to start a mock conversation with farmers, FPOs, and buyers.'], ['Where can I find schemes?', 'Government Schemes includes a short, searchable list of common farmer support programmes.']]; return <PageShell title="Help & Support" subtitle="Quick answers for your Krishi Setu demo journey."><div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 card"><h3 className="font-bold text-forest-800 mb-4">Frequently asked questions</h3>{faqs.map(([question, answer], i) => <div className="border-b border-gray-100 last:border-0" key={question}><button className="w-full flex justify-between items-center py-4 text-left font-semibold text-sm text-gray-800" onClick={() => setOpen(open === i ? null : i)}>{question}<ChevronRight size={16} className={`transition-transform ${open === i ? 'rotate-90' : ''}`} /></button>{open === i && <p className="text-sm text-gray-600 pb-4 leading-relaxed">{answer}</p>}</div>)}</div><div className="space-y-4"><div className="card"><HelpCircle size={21} className="text-forest-700" /><h3 className="font-bold text-forest-800 mt-4">Need a human?</h3><p className="text-sm text-gray-600 mt-2">Our demo support desk is available for your presentation walkthrough.</p><button className="btn-primary w-full justify-center mt-5">Start support chat</button></div><div className="card"><Mail size={19} className="text-forest-700" /><p className="text-sm font-semibold mt-3">support@krishisetu.demo</p><p className="text-xs text-agri-muted mt-1">Prototype support inbox</p></div></div></div></PageShell>; }

export function SettingsPage() { const { addToast, language, setLanguage, t } = useApp(); const [settings, setSettings] = useState(() => JSON.parse(localStorage.getItem('krishisetu_settings') || '{"alerts":true,"market":true}')); const save = () => { localStorage.setItem('krishisetu_settings', JSON.stringify(settings)); addToast(t('Settings saved locally'), 'success'); }; return <PageShell title="Settings" subtitle="Adjust your local prototype preferences."><div className="max-w-2xl card space-y-6"><div className="flex items-center gap-3"><Settings size={21} className="text-forest-700" /><div><h3 className="font-bold text-forest-800">{t('Preferences')}</h3><p className="text-xs text-agri-muted mt-1">{t('These settings stay on this device.')}</p></div></div><label className="flex items-center justify-between gap-4 py-3 border-b border-gray-100"><div><p className="font-semibold text-sm text-gray-800">{t('Order notifications')}</p><p className="text-xs text-agri-muted">{t('Get updates about delivery and payments.')}</p></div><input type="checkbox" checked={settings.alerts} onChange={e => setSettings({ ...settings, alerts: e.target.checked })} className="w-5 h-5 accent-green-700" /></label><label className="flex items-center justify-between gap-4 py-3 border-b border-gray-100"><div><p className="font-semibold text-sm text-gray-800">{t('Market alerts')}</p><p className="text-xs text-agri-muted">{t('Show crop price and demand changes.')}</p></div><input type="checkbox" checked={settings.market} onChange={e => setSettings({ ...settings, market: e.target.checked })} className="w-5 h-5 accent-green-700" /></label><label className="label">{t('Language')}<select className="select mt-1" value={language} onChange={e => setLanguage(e.target.value)}><option>English</option><option>Hindi</option></select></label><button className="btn-primary" onClick={save}><Save size={16} />{t('Save')}</button></div></PageShell>; }

function PageShell({ title, subtitle, children }) { const { t } = useApp(); return <div><div className="mb-6"><h1 className="section-title">{t(title)}</h1><p className="section-subtitle">{t(subtitle)}</p></div>{children}</div>; }
